-- Skema hpsecond. Dijalankan sekali saat container database siap, lewat
-- /docker-entrypoint-initdb.d. Semua pernyataan dibuat ulang-dijalankan dengan
-- aman supaya skrip ini boleh dipakai ulang tanpa merusak data yang sudah ada.
--
-- Berbeda dari SQLite, tidak ada perlu migrasi bertahap di sini: Postgres yang
-- pertama kali dibuat sudah dapat bentuk akhir. Blok ALTER TABLE yang dulu
-- dibangun untuk SQLite (menambah kolom satu per satu, membangun ulang tabel
-- pengguna) sengaja dibuang — sekarang tidak ada lagi database lama yang
-- perlu dikejar.
--
-- Dua keputusan yang sengaja diambil supaya migrasi tidak mengubah perilaku:
--
-- 1. Waktu disimpan sebagai epoch milidetik (BIGINT), bukan TIMESTAMPTZ.
--    Hampir semua tempat memakainya sebagai `new Date(Number(ts))` untuk
--    "2 jam lalu". Kalau dikonversi ke TIMESTAMPTZ, driver pg mengembalikan
--    objek Date, `Number(date)` jadi NaN, dan setiap label waktu di situs
--    berubah jadi rusak. BIGINT memindahkan data 1:1 tanpa efek samping.
--
-- 2. Kolom JSON (kelengkapan, catatan, foto) tetap TEXT, bukan JSONB.
--    Pembacanya `daftarJson()` melakukan JSON.parse(String(v)); kalau JSONB,
--    driver sudah mengubahnya jadi array JavaScript sehingga String() hanya
--    menghasilkan "a,b" dan isinya hilang. Tidak ada query yang butuh isi
--    JSON di dalam SQL, jadi JSONB tidak menambah apa pun.

CREATE TABLE IF NOT EXISTS pengguna (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor       TEXT NOT NULL UNIQUE,
    nama        TEXT NOT NULL,
    kata_sandi  TEXT NOT NULL,
    peran       TEXT NOT NULL DEFAULT 'seller',
    status      TEXT NOT NULL DEFAULT 'aktif',
    dibuat_pada BIGINT NOT NULL,
    sesi_versi  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS lapak (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pengguna_id INTEGER NOT NULL UNIQUE REFERENCES pengguna (id) ON DELETE CASCADE,
    slug        TEXT NOT NULL UNIQUE,
    nama        TEXT NOT NULL,
    whatsapp    TEXT NOT NULL DEFAULT '',
    deskripsi   TEXT NOT NULL DEFAULT '',
    lokasi      TEXT NOT NULL DEFAULT '',
    foto        TEXT NOT NULL DEFAULT ''
);

-- Berurutan penting: hp dibuat setelah pengguna & lapak karena pemilik_id
-- menunjuk pengguna, dan NULL berarti unit milik admin sendiri.
CREATE TABLE IF NOT EXISTS hp (
    slug            TEXT PRIMARY KEY,
    nama            TEXT NOT NULL,
    merk            TEXT NOT NULL DEFAULT '',
    seri            TEXT NOT NULL DEFAULT '',
    ram             TEXT NOT NULL DEFAULT '',
    kapasitas       TEXT NOT NULL DEFAULT '',
    warna           TEXT NOT NULL DEFAULT '',
    kondisi         TEXT NOT NULL DEFAULT 'mulus',
    harga           INTEGER NOT NULL DEFAULT 0,
    harga_asli      INTEGER,
    tersedia        BOOLEAN NOT NULL DEFAULT TRUE,
    tahun_rilis     INTEGER,
    layar           TEXT NOT NULL DEFAULT '',
    baterai         TEXT NOT NULL DEFAULT '',
    kelengkapan     TEXT NOT NULL DEFAULT '[]',
    catatan         TEXT NOT NULL DEFAULT '[]',
    deskripsi       TEXT NOT NULL DEFAULT '',
    foto            TEXT NOT NULL DEFAULT '[]',
    imei            TEXT NOT NULL DEFAULT '',
    pemilik_id      INTEGER REFERENCES pengguna (id) ON DELETE SET NULL,
    moderasi        TEXT NOT NULL DEFAULT 'tayang',
    alasan_moderasi TEXT NOT NULL DEFAULT ''
);

-- Identitas toko, kata sandi admin, dan session secret disimpan sebagai satu
-- baris per kunci supaya menambah field baru tidak perlu mengubah skema.
CREATE TABLE IF NOT EXISTS pengaturan (
    kunci TEXT PRIMARY KEY,
    nilai TEXT NOT NULL
);

-- Statistik klik WhatsApp per unit, dipangkas setelah 90 hari.
CREATE TABLE IF NOT EXISTS klik (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL,
    ts   BIGINT NOT NULL
);

-- Penghitung rate limit login. Sengaja di database, bukan di memori proses,
-- supaya kuncinya tidak hilang tepat saat container direstart.
CREATE TABLE IF NOT EXISTS percobaan (
    kunci TEXT PRIMARY KEY,
    n     INTEGER NOT NULL DEFAULT 0,
    buka  BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS pengumuman (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul       TEXT NOT NULL,
    isi         TEXT NOT NULL,
    aktif       BOOLEAN NOT NULL DEFAULT TRUE,
    dibuat_pada BIGINT NOT NULL,
    diubah_pada BIGINT NOT NULL
);

-- Satu index ini menggantikan hp_moderasi yang dulu hanya (moderasi, tersedia).
-- Katalog publik selalu menyaring moderasi + tersedia lalu mengurutkan dengan
-- harga dan slug, jadi dengan susunan ini Postgres bisa memenuhi filter dan
-- sort dari index tanpa tahap sort terpisah. Database ini kecil dan semua
-- penghitungannya milik satu proses, jadi-query tambahan ini cukup murah.
CREATE INDEX IF NOT EXISTS hp_moderasi_tersedia_harga ON hp (moderasi, tersedia, harga, slug);
CREATE INDEX IF NOT EXISTS hp_pemilik ON hp (pemilik_id);
CREATE INDEX IF NOT EXISTS klik_slug_ts ON klik (slug, ts);
-- Dipakai pangkasLama() untuk membuang kunci yang sudah kedaluwarsa.
CREATE INDEX IF NOT EXISTS percobaan_buka ON percobaan (buka);